### ISSUE TITLE
ArrayIndexOutOfBoundsException: 20

### ISSUE THREAD

**Issue by JRobinson333** [aeshell/aesh-readline#59]
Hello, I would appreciate if somebody could offer advice on why the following message occurs when calling ./jboss-cli.sh -c (the standalone service is definitely running have checked with netstat -tln).

From what I have debugged, the problem looks to be due to aesh-readline, though I suspect I am missing some package dependencies that are unclear to me.

I think the shell script is effectively calling the exec java command included below - just executing the script outputs '20' as the code exits before dumping out any useful debug message.

I'm finding this particularly frustrating as I have managed on a previous setup to gain access to the interactive CLI and it seems having followed the same steps I am no longer able to do so. Of course, there is probably some discrepancy between the steps I took. This is on an AlpineLinux 3.14.2-virt kernel (though I've attempted using different versions on various VMs) and I can post more details if helpful. aesh-readline looks to depend on a number of software packages having tried to deploy just that with maven. Adding emacs, readline, ncurses and ncurses-terminfo (for infocmp command) progressed the maven deployment further, but it still bombed out.

$ exec "$JAVA_HOME"/bin/java -jar /opt/wildfly/jboss-modules.jar -mp /op
t/wildfly/modules org.jboss.as.cli
INFO  [org.jboss.modules] JBoss Modules version 1.9.1.Final
WARN: can't find jboss-cli.xml. Using default configuration values.
INFO  [org.jboss.as.cli.CommandContext] You are disconnected at the moment. Type 'connect' to connect to the server or 'help' for the list of supported commands.
You are disconnected at the moment. Type 'connect' to connect to the server or 'help' for the list of supported commands.
20
ERROR [org.jboss.as.cli.impl.CliLauncher] Error processing CLI: java.lang.ArrayIndexOutOfBoundsException: 20
        at org.aesh.readline.terminal.impl.ExecPty.doGetLinuxAttr(ExecPty.java:278)
        at org.aesh.readline.terminal.impl.ExecPty.getAttr(ExecPty.java:136)
        at org.aesh.readline.terminal.impl.AbstractPosixTerminal.<init>(AbstractPosixTerminal.java:37)
        at org.aesh.readline.terminal.impl.PosixSysTerminal.<init>(PosixSysTerminal.java:40)
        at org.aesh.readline.terminal.TerminalBuilder.build(TerminalBuilder.java:132)
        at org.jboss.as.cli.impl.ReadlineConsole.newConnection(ReadlineConsole.java:529)
        at org.jboss.as.cli.impl.ReadlineConsole.initializeConnection(ReadlineConsole.java:473)
        at org.jboss.as.cli.impl.ReadlineConsole.start(ReadlineConsole.java:813)
        at org.jboss.as.cli.impl.CommandContextImpl.interact(CommandContextImpl.java:1898)
        at org.jboss.as.cli.impl.CliLauncher.main(CliLauncher.java:314)
        at org.jboss.as.cli.CommandLineMain.main(CommandLineMain.java:45)
        at org.jboss.modules.Module.run(Module.java:352)
        at org.jboss.modules.Module.run(Module.java:320)
        at org.jboss.modules.Main.main(Main.java:593)

**Comment by JRobinson333** [comment]
I should add that I'm using Putty to connect via SSH, and it has crossed my mind that this might be being caused by Putty settings?

**Comment by JRobinson333** [comment]
After checking here:
https://github.com/aeshell/aesh-readline/blob/655008ade67f8622c460316a8299bae61cdef8ba/readline/src/main/java/org/aesh/readline/terminal/impl/ExecPty.java

My attention is drawn to ~ Ln 240 protected string doGetConfig()

stty doesn't exist on the AlpineLinux in use (ttyS0 is being used inside virsh)

I created a symbolic link from tty to stty
ln -s /dev/tty /dev/stty
chown -h root.tty /dev/stty

It outputs as follows:
speed 115200 baud; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol =
; eol2 = <undef>;
swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W;
lnext = ^V; flush = ^O; min = 1; time = 0;
-brkint ixoff -imaxbel
-iexten

**Comment by JRobinson333** [comment]
For anyone else that stumbles into this problems, you can resolve the issue by running:
apk add coreutils

The stty version build in this package outputs in a format that can be consumed by the Java in aesh-readline.
